# coding=utf-8 
import web
import sys
import os

# 渲染html
g_render = web.template.render('templates/')

# 当前session上传文件新建版本所需存的数据
FILEPATH = "FILEPATH"
FILENAME = "FILENAME"
FILEHASH = "FILEHASH"
FILESIZE = "FILESIZE"

ADD_FILES = "ADD_FILES"  # {ADD_FILES_FILEPATH : {ADD_FILES_FILENAME, ADD_FILES_PROJECT_GROUP_NAME, ADD_FILES_FILEHASH, ADD_FILES_FILESIZE}}
ADD_FILES_FILEPATH = FILEPATH
ADD_FILES_FILENAME = FILENAME
ADD_FILES_FILEHASH = FILEHASH
ADD_FILES_FILESIZE = FILESIZE
ADD_FILES_PROJECT_GROUP_NAME = "PROJECT_GROUP_NAME"

MOD_FILES = "MOD_FILES"   # {MOD_FILES_FILEPATH : {MOD_FILES_FILENAME, MOD_FILES_FILEHASH, MOD_FILES_FILESIZE}}
MOD_FILES_FILEPATH = FILEPATH
MOD_FILES_FILENAME = FILENAME
MOD_FILES_FILEHASH = FILEHASH
MOD_FILES_FILESIZE = FILESIZE

g_new_version = {
    ADD_FILES : {},
    MOD_FILES : {}
}